baseURL = "https://muhammad-sulaiman.com"
languageCode = "en-us"
title = "Muhammad Sulaiman"
theme = "careercanvas"
publishDir = "docs"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
    [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
    [languages.en.params]
        tagline = "Project Manager, Software Engineer."
        hero_description = "Technical project manager and software developer with 7+ years in the IT industry. Bachelorâ€™s degree in Computer Science and Masterâ€™s degree in AI/NLP. Experienced software architect and tech lead, open source enthusiast, curious mind, and lifelong learner who turns ideas into working code."
        hero_location = "Damascus, Syria"
        collab_tags = [
            "Technical Project Management",
            "Software Architecture",
            "Team leadership",
            "AI/NLP Solutions",
            "Technical Consulting",
            ".NET Development",
            "Desktop & Mobile Applications",
            "Web Applications",
        ]

[build]
writeStats = true

[params]
name = "Muhammad Sulaiman"
location = "Damascus, Syria"
email = "muhammad.b.sulaiman@gmail.com"
profile_image = "/images/muhammad-sulaiman-image.jpg"
# Project manager, software architect, programmer, master's degree in AI/NLP & open source enthusiast.\nHusband & Father of two, passionate about building intelligent solutions for complex engineering problems
description = "32 Year old Muslim ğŸ‘³ğŸ» Husband ğŸ¤µ, Father of 2 ğŸ‘§ğŸ»ğŸ‘¦ğŸ». Religion first, family second.. sport, science and code = a way of life."
author = "Mo Sulaiman"

og_image = "images/muhammad-sulaiman-image.jpg"

linkedin_url = "https://www.linkedin.com/in/muhammad-sulaiman-b3723ba6"
linkedin_text = "linkedin.com/in/muhammad-sulaiman-b3723ba6"
github_url = "https://github.com/MuhammadSulaiman001"
github_text = "github.com/MuhammadSulaiman001"

copyright = "Â© 2025 | Muhammad Sulaiman"

resume_url_en = "/files/sulaiman-resume.pdf"
resume_label = "View CV"

formspree_endpoint = "https://formspree.io/f/mzzvjzee" # Change to your Formspree endpoint - DONE

[[params.social]]
icon = "linkedin-in"
url = "https://www.linkedin.com/in/muhammad-sulaiman-b3723ba6/"

[[params.social]]
icon = "github"
url = "https://github.com/MuhammadSulaiman001"

sectionPagesMenu = 'main'

[taxonomies]
tag = "tags"


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokai"

[server]
[[server.headers]]
for = "/**/*.css"
[server.headers.values]
Content-Type = "text/css"


# Branding Configuration - Savannah King
[params.colors]
# main_color   = "#A97142"  # Lion Brown, warm and dominant
# second_color = "#2E2E2E"  # Dark Charcoal, authority
# third_color  = "#E6B325"  # Golden Mane, majesty and power
main_color   = "#095BB0"  # Slightly Darker LinkedIn Blue, professional and trustworthy
second_color = "#004182"  # Darker Blue, for depth and sophistication
third_color  = "#8C8C8C"  # Neutral Gray, for balance and modernity